// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 497836589;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__preview__append_paths_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "append_paths",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_existing_paths = <Vec<String>>::sse_decode(&mut deserializer);
            let api_new_paths = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::preview::append_paths(api_existing_paths, api_new_paths)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__receiver__current_receiver_registration_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "current_receiver_registration",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::receiver::current_receiver_registration())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__receiver__ensure_receiver_registration_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ensure_receiver_registration",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_url = <Option<String>>::sse_decode(&mut deserializer);
            let api_device_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::receiver::ensure_receiver_registration(
                        api_server_url,
                        api_device_name,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__preview__inspect_paths_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "inspect_paths",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_paths = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::preview::inspect_paths(api_paths)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__device__random_device_name_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "random_device_name",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::device::random_device_name())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__receiver__register_receiver_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "register_receiver",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_url = <Option<String>>::sse_decode(&mut deserializer);
            let api_device_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::receiver::register_receiver(api_server_url, api_device_name)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__preview__remove_path_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "remove_path",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_existing_paths = <Vec<String>>::sse_decode(&mut deserializer);
            let api_removed_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::preview::remove_path(api_existing_paths, api_removed_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__receiver__respond_to_receiver_offer_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "respond_to_receiver_offer",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_accept = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::receiver::respond_to_receiver_offer(api_accept)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__lan__scan_nearby_receivers_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scan_nearby_receivers",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::lan::scan_nearby_receivers(api_timeout_secs)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__receiver__set_receiver_discoverable_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_receiver_discoverable",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_enabled = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::receiver::set_receiver_discoverable(api_enabled)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__receiver__start_receiver_transfer_listener_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_receiver_transfer_listener",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_download_root = <String>::sse_decode(&mut deserializer);
            let api_device_name = <String>::sse_decode(&mut deserializer);
            let api_device_type = <String>::sse_decode(&mut deserializer);
            let api_updates = <StreamSink<
                crate::api::receiver::ReceiverTransferEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::receiver::start_receiver_transfer_listener(
                        api_download_root,
                        api_device_name,
                        api_device_type,
                        api_updates,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__sender__start_send_transfer_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_send_transfer",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::sender::SendTransferRequest>::sse_decode(&mut deserializer);
            let api_updates = <StreamSink<
                crate::api::sender::SendTransferEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::sender::start_send_transfer(api_request, api_updates)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__receiver__watch_receiver_pairing_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "watch_receiver_pairing",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_download_root = <String>::sse_decode(&mut deserializer);
            let api_device_name = <String>::sse_decode(&mut deserializer);
            let api_device_type = <String>::sse_decode(&mut deserializer);
            let api_updates = <StreamSink<
                crate::api::receiver::ReceiverPairingState,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::receiver::watch_receiver_pairing(
                        api_download_root,
                        api_device_name,
                        api_device_type,
                        api_updates,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::receiver::ReceiverPairingState,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::receiver::ReceiverTransferEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::sender::SendTransferEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::lan::NearbyReceiverInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::lan::NearbyReceiverInfo>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::receiver::ReceiverTransferFile> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::receiver::ReceiverTransferFile>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::preview::SelectionItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::preview::SelectionItem>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::lan::NearbyReceiverInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_fullname = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_code = <String>::sse_decode(deserializer);
        let mut var_ticket = <String>::sse_decode(deserializer);
        return crate::api::lan::NearbyReceiverInfo {
            fullname: var_fullname,
            label: var_label,
            code: var_code,
            ticket: var_ticket,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::receiver::ReceiverRegistration> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::receiver::ReceiverRegistration>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::receiver::ReceiverPairingState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <Option<String>>::sse_decode(deserializer);
        let mut var_expiresAt = <Option<String>>::sse_decode(deserializer);
        return crate::api::receiver::ReceiverPairingState {
            code: var_code,
            expires_at: var_expiresAt,
        };
    }
}

impl SseDecode for crate::api::receiver::ReceiverRegistration {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <String>::sse_decode(deserializer);
        let mut var_expiresAt = <String>::sse_decode(deserializer);
        return crate::api::receiver::ReceiverRegistration {
            code: var_code,
            expires_at: var_expiresAt,
        };
    }
}

impl SseDecode for crate::api::receiver::ReceiverTransferEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_phase = <crate::api::receiver::ReceiverTransferPhase>::sse_decode(deserializer);
        let mut var_senderName = <String>::sse_decode(deserializer);
        let mut var_destinationLabel = <String>::sse_decode(deserializer);
        let mut var_saveRootLabel = <String>::sse_decode(deserializer);
        let mut var_statusMessage = <String>::sse_decode(deserializer);
        let mut var_itemCount = <u64>::sse_decode(deserializer);
        let mut var_totalSizeBytes = <u64>::sse_decode(deserializer);
        let mut var_totalSizeLabel = <String>::sse_decode(deserializer);
        let mut var_files =
            <Vec<crate::api::receiver::ReceiverTransferFile>>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::receiver::ReceiverTransferEvent {
            phase: var_phase,
            sender_name: var_senderName,
            destination_label: var_destinationLabel,
            save_root_label: var_saveRootLabel,
            status_message: var_statusMessage,
            item_count: var_itemCount,
            total_size_bytes: var_totalSizeBytes,
            total_size_label: var_totalSizeLabel,
            files: var_files,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::api::receiver::ReceiverTransferFile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_size = <u64>::sse_decode(deserializer);
        return crate::api::receiver::ReceiverTransferFile {
            path: var_path,
            size: var_size,
        };
    }
}

impl SseDecode for crate::api::receiver::ReceiverTransferPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::receiver::ReceiverTransferPhase::Connecting,
            1 => crate::api::receiver::ReceiverTransferPhase::OfferReady,
            2 => crate::api::receiver::ReceiverTransferPhase::Receiving,
            3 => crate::api::receiver::ReceiverTransferPhase::Completed,
            4 => crate::api::receiver::ReceiverTransferPhase::Failed,
            5 => crate::api::receiver::ReceiverTransferPhase::Declined,
            _ => unreachable!("Invalid variant for ReceiverTransferPhase: {}", inner),
        };
    }
}

impl SseDecode for crate::api::preview::SelectionItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_isDirectory = <bool>::sse_decode(deserializer);
        let mut var_fileCount = <u64>::sse_decode(deserializer);
        let mut var_totalSize = <u64>::sse_decode(deserializer);
        return crate::api::preview::SelectionItem {
            name: var_name,
            path: var_path,
            is_directory: var_isDirectory,
            file_count: var_fileCount,
            total_size: var_totalSize,
        };
    }
}

impl SseDecode for crate::api::preview::SelectionPreview {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_items = <Vec<crate::api::preview::SelectionItem>>::sse_decode(deserializer);
        let mut var_fileCount = <u64>::sse_decode(deserializer);
        let mut var_totalSize = <u64>::sse_decode(deserializer);
        return crate::api::preview::SelectionPreview {
            items: var_items,
            file_count: var_fileCount,
            total_size: var_totalSize,
        };
    }
}

impl SseDecode for crate::api::sender::SendTransferEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_phase = <crate::api::sender::SendTransferPhase>::sse_decode(deserializer);
        let mut var_destinationLabel = <String>::sse_decode(deserializer);
        let mut var_statusMessage = <String>::sse_decode(deserializer);
        let mut var_itemCount = <u64>::sse_decode(deserializer);
        let mut var_totalSize = <u64>::sse_decode(deserializer);
        let mut var_bytesSent = <u64>::sse_decode(deserializer);
        let mut var_remoteDeviceType = <Option<String>>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::sender::SendTransferEvent {
            phase: var_phase,
            destination_label: var_destinationLabel,
            status_message: var_statusMessage,
            item_count: var_itemCount,
            total_size: var_totalSize,
            bytes_sent: var_bytesSent,
            remote_device_type: var_remoteDeviceType,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::api::sender::SendTransferPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::sender::SendTransferPhase::Connecting,
            1 => crate::api::sender::SendTransferPhase::WaitingForDecision,
            2 => crate::api::sender::SendTransferPhase::Sending,
            3 => crate::api::sender::SendTransferPhase::Completed,
            4 => crate::api::sender::SendTransferPhase::Failed,
            _ => unreachable!("Invalid variant for SendTransferPhase: {}", inner),
        };
    }
}

impl SseDecode for crate::api::sender::SendTransferRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <String>::sse_decode(deserializer);
        let mut var_paths = <Vec<String>>::sse_decode(deserializer);
        let mut var_serverUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_deviceName = <String>::sse_decode(deserializer);
        let mut var_deviceType = <String>::sse_decode(deserializer);
        let mut var_ticket = <Option<String>>::sse_decode(deserializer);
        let mut var_lanDestinationLabel = <Option<String>>::sse_decode(deserializer);
        return crate::api::sender::SendTransferRequest {
            code: var_code,
            paths: var_paths,
            server_url: var_serverUrl,
            device_name: var_deviceName,
            device_type: var_deviceType,
            ticket: var_ticket,
            lan_destination_label: var_lanDestinationLabel,
        };
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__preview__append_paths_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__receiver__current_receiver_registration_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__receiver__ensure_receiver_registration_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__preview__inspect_paths_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__receiver__register_receiver_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__preview__remove_path_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__receiver__respond_to_receiver_offer_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        11 => wire__crate__api__lan__scan_nearby_receivers_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__receiver__set_receiver_discoverable_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        13 => wire__crate__api__receiver__start_receiver_transfer_listener_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        14 => wire__crate__api__sender__start_send_transfer_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__api__receiver__watch_receiver_pairing_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        4 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__device__random_device_name_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::lan::NearbyReceiverInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.fullname.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.code.into_into_dart().into_dart(),
            self.ticket.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::lan::NearbyReceiverInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::lan::NearbyReceiverInfo>
    for crate::api::lan::NearbyReceiverInfo
{
    fn into_into_dart(self) -> crate::api::lan::NearbyReceiverInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::receiver::ReceiverPairingState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.expires_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::receiver::ReceiverPairingState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::receiver::ReceiverPairingState>
    for crate::api::receiver::ReceiverPairingState
{
    fn into_into_dart(self) -> crate::api::receiver::ReceiverPairingState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::receiver::ReceiverRegistration {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.expires_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::receiver::ReceiverRegistration
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::receiver::ReceiverRegistration>
    for crate::api::receiver::ReceiverRegistration
{
    fn into_into_dart(self) -> crate::api::receiver::ReceiverRegistration {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::receiver::ReceiverTransferEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.phase.into_into_dart().into_dart(),
            self.sender_name.into_into_dart().into_dart(),
            self.destination_label.into_into_dart().into_dart(),
            self.save_root_label.into_into_dart().into_dart(),
            self.status_message.into_into_dart().into_dart(),
            self.item_count.into_into_dart().into_dart(),
            self.total_size_bytes.into_into_dart().into_dart(),
            self.total_size_label.into_into_dart().into_dart(),
            self.files.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::receiver::ReceiverTransferEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::receiver::ReceiverTransferEvent>
    for crate::api::receiver::ReceiverTransferEvent
{
    fn into_into_dart(self) -> crate::api::receiver::ReceiverTransferEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::receiver::ReceiverTransferFile {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::receiver::ReceiverTransferFile
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::receiver::ReceiverTransferFile>
    for crate::api::receiver::ReceiverTransferFile
{
    fn into_into_dart(self) -> crate::api::receiver::ReceiverTransferFile {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::receiver::ReceiverTransferPhase {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Connecting => 0.into_dart(),
            Self::OfferReady => 1.into_dart(),
            Self::Receiving => 2.into_dart(),
            Self::Completed => 3.into_dart(),
            Self::Failed => 4.into_dart(),
            Self::Declined => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::receiver::ReceiverTransferPhase
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::receiver::ReceiverTransferPhase>
    for crate::api::receiver::ReceiverTransferPhase
{
    fn into_into_dart(self) -> crate::api::receiver::ReceiverTransferPhase {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::preview::SelectionItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.is_directory.into_into_dart().into_dart(),
            self.file_count.into_into_dart().into_dart(),
            self.total_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::preview::SelectionItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::preview::SelectionItem>
    for crate::api::preview::SelectionItem
{
    fn into_into_dart(self) -> crate::api::preview::SelectionItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::preview::SelectionPreview {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.items.into_into_dart().into_dart(),
            self.file_count.into_into_dart().into_dart(),
            self.total_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::preview::SelectionPreview
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::preview::SelectionPreview>
    for crate::api::preview::SelectionPreview
{
    fn into_into_dart(self) -> crate::api::preview::SelectionPreview {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sender::SendTransferEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.phase.into_into_dart().into_dart(),
            self.destination_label.into_into_dart().into_dart(),
            self.status_message.into_into_dart().into_dart(),
            self.item_count.into_into_dart().into_dart(),
            self.total_size.into_into_dart().into_dart(),
            self.bytes_sent.into_into_dart().into_dart(),
            self.remote_device_type.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sender::SendTransferEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sender::SendTransferEvent>
    for crate::api::sender::SendTransferEvent
{
    fn into_into_dart(self) -> crate::api::sender::SendTransferEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sender::SendTransferPhase {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Connecting => 0.into_dart(),
            Self::WaitingForDecision => 1.into_dart(),
            Self::Sending => 2.into_dart(),
            Self::Completed => 3.into_dart(),
            Self::Failed => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sender::SendTransferPhase
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sender::SendTransferPhase>
    for crate::api::sender::SendTransferPhase
{
    fn into_into_dart(self) -> crate::api::sender::SendTransferPhase {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sender::SendTransferRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.paths.into_into_dart().into_dart(),
            self.server_url.into_into_dart().into_dart(),
            self.device_name.into_into_dart().into_dart(),
            self.device_type.into_into_dart().into_dart(),
            self.ticket.into_into_dart().into_dart(),
            self.lan_destination_label.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sender::SendTransferRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sender::SendTransferRequest>
    for crate::api::sender::SendTransferRequest
{
    fn into_into_dart(self) -> crate::api::sender::SendTransferRequest {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::receiver::ReceiverPairingState,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::receiver::ReceiverTransferEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::sender::SendTransferEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::lan::NearbyReceiverInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::lan::NearbyReceiverInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::receiver::ReceiverTransferFile> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::receiver::ReceiverTransferFile>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::preview::SelectionItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::preview::SelectionItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::lan::NearbyReceiverInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.fullname, serializer);
        <String>::sse_encode(self.label, serializer);
        <String>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.ticket, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::receiver::ReceiverRegistration> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::receiver::ReceiverRegistration>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::receiver::ReceiverPairingState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.code, serializer);
        <Option<String>>::sse_encode(self.expires_at, serializer);
    }
}

impl SseEncode for crate::api::receiver::ReceiverRegistration {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.expires_at, serializer);
    }
}

impl SseEncode for crate::api::receiver::ReceiverTransferEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::receiver::ReceiverTransferPhase>::sse_encode(self.phase, serializer);
        <String>::sse_encode(self.sender_name, serializer);
        <String>::sse_encode(self.destination_label, serializer);
        <String>::sse_encode(self.save_root_label, serializer);
        <String>::sse_encode(self.status_message, serializer);
        <u64>::sse_encode(self.item_count, serializer);
        <u64>::sse_encode(self.total_size_bytes, serializer);
        <String>::sse_encode(self.total_size_label, serializer);
        <Vec<crate::api::receiver::ReceiverTransferFile>>::sse_encode(self.files, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::api::receiver::ReceiverTransferFile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <u64>::sse_encode(self.size, serializer);
    }
}

impl SseEncode for crate::api::receiver::ReceiverTransferPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::receiver::ReceiverTransferPhase::Connecting => 0,
                crate::api::receiver::ReceiverTransferPhase::OfferReady => 1,
                crate::api::receiver::ReceiverTransferPhase::Receiving => 2,
                crate::api::receiver::ReceiverTransferPhase::Completed => 3,
                crate::api::receiver::ReceiverTransferPhase::Failed => 4,
                crate::api::receiver::ReceiverTransferPhase::Declined => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::preview::SelectionItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.path, serializer);
        <bool>::sse_encode(self.is_directory, serializer);
        <u64>::sse_encode(self.file_count, serializer);
        <u64>::sse_encode(self.total_size, serializer);
    }
}

impl SseEncode for crate::api::preview::SelectionPreview {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::preview::SelectionItem>>::sse_encode(self.items, serializer);
        <u64>::sse_encode(self.file_count, serializer);
        <u64>::sse_encode(self.total_size, serializer);
    }
}

impl SseEncode for crate::api::sender::SendTransferEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::sender::SendTransferPhase>::sse_encode(self.phase, serializer);
        <String>::sse_encode(self.destination_label, serializer);
        <String>::sse_encode(self.status_message, serializer);
        <u64>::sse_encode(self.item_count, serializer);
        <u64>::sse_encode(self.total_size, serializer);
        <u64>::sse_encode(self.bytes_sent, serializer);
        <Option<String>>::sse_encode(self.remote_device_type, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::api::sender::SendTransferPhase {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::sender::SendTransferPhase::Connecting => 0,
                crate::api::sender::SendTransferPhase::WaitingForDecision => 1,
                crate::api::sender::SendTransferPhase::Sending => 2,
                crate::api::sender::SendTransferPhase::Completed => 3,
                crate::api::sender::SendTransferPhase::Failed => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::sender::SendTransferRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.code, serializer);
        <Vec<String>>::sse_encode(self.paths, serializer);
        <Option<String>>::sse_encode(self.server_url, serializer);
        <String>::sse_encode(self.device_name, serializer);
        <String>::sse_encode(self.device_type, serializer);
        <Option<String>>::sse_encode(self.ticket, serializer);
        <Option<String>>::sse_encode(self.lan_destination_label, serializer);
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
