// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/device.dart';
import 'api/error.dart';
import 'api/lan.dart';
import 'api/preview.dart';
import 'api/receiver.dart';
import 'api/sender.dart';
import 'api/simple.dart';
import 'api/transfer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ReceiverPairingState>
  dco_decode_StreamSink_receiver_pairing_state_Sse(dynamic raw);

  @protected
  RustStreamSink<ReceiverTransferEvent>
  dco_decode_StreamSink_receiver_transfer_event_Sse(dynamic raw);

  @protected
  RustStreamSink<SendTransferEvent>
  dco_decode_StreamSink_send_transfer_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ReceiverRegistration dco_decode_box_autoadd_receiver_registration(
    dynamic raw,
  );

  @protected
  SendTransferRequest dco_decode_box_autoadd_send_transfer_request(dynamic raw);

  @protected
  TransferPlanData dco_decode_box_autoadd_transfer_plan_data(dynamic raw);

  @protected
  TransferSnapshotData dco_decode_box_autoadd_transfer_snapshot_data(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UserFacingErrorData dco_decode_box_autoadd_user_facing_error_data(
    dynamic raw,
  );

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<NearbyReceiverInfo> dco_decode_list_nearby_receiver_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReceiverTransferFile> dco_decode_list_receiver_transfer_file(
    dynamic raw,
  );

  @protected
  List<SelectionItem> dco_decode_list_selection_item(dynamic raw);

  @protected
  List<TransferPlanFileData> dco_decode_list_transfer_plan_file_data(
    dynamic raw,
  );

  @protected
  NearbyReceiverInfo dco_decode_nearby_receiver_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ReceiverRegistration? dco_decode_opt_box_autoadd_receiver_registration(
    dynamic raw,
  );

  @protected
  TransferPlanData? dco_decode_opt_box_autoadd_transfer_plan_data(dynamic raw);

  @protected
  TransferSnapshotData? dco_decode_opt_box_autoadd_transfer_snapshot_data(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  UserFacingErrorData? dco_decode_opt_box_autoadd_user_facing_error_data(
    dynamic raw,
  );

  @protected
  ReceiverPairingState dco_decode_receiver_pairing_state(dynamic raw);

  @protected
  ReceiverRegistration dco_decode_receiver_registration(dynamic raw);

  @protected
  ReceiverTransferEvent dco_decode_receiver_transfer_event(dynamic raw);

  @protected
  ReceiverTransferFile dco_decode_receiver_transfer_file(dynamic raw);

  @protected
  ReceiverTransferPhase dco_decode_receiver_transfer_phase(dynamic raw);

  @protected
  SelectionItem dco_decode_selection_item(dynamic raw);

  @protected
  SelectionPreview dco_decode_selection_preview(dynamic raw);

  @protected
  SendTransferEvent dco_decode_send_transfer_event(dynamic raw);

  @protected
  SendTransferPhase dco_decode_send_transfer_phase(dynamic raw);

  @protected
  SendTransferRequest dco_decode_send_transfer_request(dynamic raw);

  @protected
  TransferPhaseData dco_decode_transfer_phase_data(dynamic raw);

  @protected
  TransferPlanData dco_decode_transfer_plan_data(dynamic raw);

  @protected
  TransferPlanFileData dco_decode_transfer_plan_file_data(dynamic raw);

  @protected
  TransferSnapshotData dco_decode_transfer_snapshot_data(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserFacingErrorData dco_decode_user_facing_error_data(dynamic raw);

  @protected
  UserFacingErrorKindData dco_decode_user_facing_error_kind_data(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ReceiverPairingState>
  sse_decode_StreamSink_receiver_pairing_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ReceiverTransferEvent>
  sse_decode_StreamSink_receiver_transfer_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SendTransferEvent>
  sse_decode_StreamSink_send_transfer_event_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ReceiverRegistration sse_decode_box_autoadd_receiver_registration(
    SseDeserializer deserializer,
  );

  @protected
  SendTransferRequest sse_decode_box_autoadd_send_transfer_request(
    SseDeserializer deserializer,
  );

  @protected
  TransferPlanData sse_decode_box_autoadd_transfer_plan_data(
    SseDeserializer deserializer,
  );

  @protected
  TransferSnapshotData sse_decode_box_autoadd_transfer_snapshot_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UserFacingErrorData sse_decode_box_autoadd_user_facing_error_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<NearbyReceiverInfo> sse_decode_list_nearby_receiver_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReceiverTransferFile> sse_decode_list_receiver_transfer_file(
    SseDeserializer deserializer,
  );

  @protected
  List<SelectionItem> sse_decode_list_selection_item(
    SseDeserializer deserializer,
  );

  @protected
  List<TransferPlanFileData> sse_decode_list_transfer_plan_file_data(
    SseDeserializer deserializer,
  );

  @protected
  NearbyReceiverInfo sse_decode_nearby_receiver_info(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ReceiverRegistration? sse_decode_opt_box_autoadd_receiver_registration(
    SseDeserializer deserializer,
  );

  @protected
  TransferPlanData? sse_decode_opt_box_autoadd_transfer_plan_data(
    SseDeserializer deserializer,
  );

  @protected
  TransferSnapshotData? sse_decode_opt_box_autoadd_transfer_snapshot_data(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UserFacingErrorData? sse_decode_opt_box_autoadd_user_facing_error_data(
    SseDeserializer deserializer,
  );

  @protected
  ReceiverPairingState sse_decode_receiver_pairing_state(
    SseDeserializer deserializer,
  );

  @protected
  ReceiverRegistration sse_decode_receiver_registration(
    SseDeserializer deserializer,
  );

  @protected
  ReceiverTransferEvent sse_decode_receiver_transfer_event(
    SseDeserializer deserializer,
  );

  @protected
  ReceiverTransferFile sse_decode_receiver_transfer_file(
    SseDeserializer deserializer,
  );

  @protected
  ReceiverTransferPhase sse_decode_receiver_transfer_phase(
    SseDeserializer deserializer,
  );

  @protected
  SelectionItem sse_decode_selection_item(SseDeserializer deserializer);

  @protected
  SelectionPreview sse_decode_selection_preview(SseDeserializer deserializer);

  @protected
  SendTransferEvent sse_decode_send_transfer_event(
    SseDeserializer deserializer,
  );

  @protected
  SendTransferPhase sse_decode_send_transfer_phase(
    SseDeserializer deserializer,
  );

  @protected
  SendTransferRequest sse_decode_send_transfer_request(
    SseDeserializer deserializer,
  );

  @protected
  TransferPhaseData sse_decode_transfer_phase_data(
    SseDeserializer deserializer,
  );

  @protected
  TransferPlanData sse_decode_transfer_plan_data(SseDeserializer deserializer);

  @protected
  TransferPlanFileData sse_decode_transfer_plan_file_data(
    SseDeserializer deserializer,
  );

  @protected
  TransferSnapshotData sse_decode_transfer_snapshot_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserFacingErrorData sse_decode_user_facing_error_data(
    SseDeserializer deserializer,
  );

  @protected
  UserFacingErrorKindData sse_decode_user_facing_error_kind_data(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_receiver_pairing_state_Sse(
    RustStreamSink<ReceiverPairingState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_receiver_transfer_event_Sse(
    RustStreamSink<ReceiverTransferEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_send_transfer_event_Sse(
    RustStreamSink<SendTransferEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_receiver_registration(
    ReceiverRegistration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_send_transfer_request(
    SendTransferRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transfer_plan_data(
    TransferPlanData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transfer_snapshot_data(
    TransferSnapshotData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_facing_error_data(
    UserFacingErrorData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_nearby_receiver_info(
    List<NearbyReceiverInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_receiver_transfer_file(
    List<ReceiverTransferFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_selection_item(
    List<SelectionItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_plan_file_data(
    List<TransferPlanFileData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nearby_receiver_info(
    NearbyReceiverInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_receiver_registration(
    ReceiverRegistration? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_transfer_plan_data(
    TransferPlanData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_transfer_snapshot_data(
    TransferSnapshotData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_facing_error_data(
    UserFacingErrorData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_receiver_pairing_state(
    ReceiverPairingState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_receiver_registration(
    ReceiverRegistration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_receiver_transfer_event(
    ReceiverTransferEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_receiver_transfer_file(
    ReceiverTransferFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_receiver_transfer_phase(
    ReceiverTransferPhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_selection_item(SelectionItem self, SseSerializer serializer);

  @protected
  void sse_encode_selection_preview(
    SelectionPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_transfer_event(
    SendTransferEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_transfer_phase(
    SendTransferPhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_transfer_request(
    SendTransferRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_phase_data(
    TransferPhaseData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_plan_data(
    TransferPlanData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_plan_file_data(
    TransferPlanFileData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_snapshot_data(
    TransferSnapshotData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_facing_error_data(
    UserFacingErrorData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_facing_error_kind_data(
    UserFacingErrorKindData self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
