// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/device.dart';
import 'api/lan.dart';
import 'api/preview.dart';
import 'api/receiver.dart';
import 'api/sender.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 497836589;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'drift_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<SelectionPreview> crateApiPreviewAppendPaths({
    required List<String> existingPaths,
    required List<String> newPaths,
  });

  Future<ReceiverRegistration?> crateApiReceiverCurrentReceiverRegistration();

  Future<ReceiverRegistration> crateApiReceiverEnsureReceiverRegistration({
    String? serverUrl,
    required String deviceName,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<SelectionPreview> crateApiPreviewInspectPaths({
    required List<String> paths,
  });

  String crateApiDeviceRandomDeviceName();

  Future<ReceiverRegistration> crateApiReceiverRegisterReceiver({
    String? serverUrl,
    required String deviceName,
  });

  Future<SelectionPreview> crateApiPreviewRemovePath({
    required List<String> existingPaths,
    required String removedPath,
  });

  Future<void> crateApiReceiverRespondToReceiverOffer({required bool accept});

  Future<List<NearbyReceiverInfo>> crateApiLanScanNearbyReceivers({
    required BigInt timeoutSecs,
  });

  Future<void> crateApiReceiverSetReceiverDiscoverable({required bool enabled});

  Stream<ReceiverTransferEvent> crateApiReceiverStartReceiverTransferListener({
    required String downloadRoot,
    required String deviceName,
    required String deviceType,
  });

  Stream<SendTransferEvent> crateApiSenderStartSendTransfer({
    required SendTransferRequest request,
  });

  Stream<ReceiverPairingState> crateApiReceiverWatchReceiverPairing({
    required String downloadRoot,
    required String deviceName,
    required String deviceType,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SelectionPreview> crateApiPreviewAppendPaths({
    required List<String> existingPaths,
    required List<String> newPaths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(existingPaths, serializer);
          sse_encode_list_String(newPaths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_selection_preview,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPreviewAppendPathsConstMeta,
        argValues: [existingPaths, newPaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreviewAppendPathsConstMeta => const TaskConstMeta(
    debugName: "append_paths",
    argNames: ["existingPaths", "newPaths"],
  );

  @override
  Future<ReceiverRegistration?> crateApiReceiverCurrentReceiverRegistration() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_receiver_registration,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReceiverCurrentReceiverRegistrationConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverCurrentReceiverRegistrationConstMeta =>
      const TaskConstMeta(
        debugName: "current_receiver_registration",
        argNames: [],
      );

  @override
  Future<ReceiverRegistration> crateApiReceiverEnsureReceiverRegistration({
    String? serverUrl,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(serverUrl, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_registration,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReceiverEnsureReceiverRegistrationConstMeta,
        argValues: [serverUrl, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverEnsureReceiverRegistrationConstMeta =>
      const TaskConstMeta(
        debugName: "ensure_receiver_registration",
        argNames: ["serverUrl", "deviceName"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<SelectionPreview> crateApiPreviewInspectPaths({
    required List<String> paths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_selection_preview,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPreviewInspectPathsConstMeta,
        argValues: [paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreviewInspectPathsConstMeta =>
      const TaskConstMeta(debugName: "inspect_paths", argNames: ["paths"]);

  @override
  String crateApiDeviceRandomDeviceName() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeviceRandomDeviceNameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceRandomDeviceNameConstMeta =>
      const TaskConstMeta(debugName: "random_device_name", argNames: []);

  @override
  Future<ReceiverRegistration> crateApiReceiverRegisterReceiver({
    String? serverUrl,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(serverUrl, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_registration,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReceiverRegisterReceiverConstMeta,
        argValues: [serverUrl, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverRegisterReceiverConstMeta =>
      const TaskConstMeta(
        debugName: "register_receiver",
        argNames: ["serverUrl", "deviceName"],
      );

  @override
  Future<SelectionPreview> crateApiPreviewRemovePath({
    required List<String> existingPaths,
    required String removedPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(existingPaths, serializer);
          sse_encode_String(removedPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_selection_preview,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPreviewRemovePathConstMeta,
        argValues: [existingPaths, removedPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreviewRemovePathConstMeta => const TaskConstMeta(
    debugName: "remove_path",
    argNames: ["existingPaths", "removedPath"],
  );

  @override
  Future<void> crateApiReceiverRespondToReceiverOffer({required bool accept}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(accept, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReceiverRespondToReceiverOfferConstMeta,
        argValues: [accept],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverRespondToReceiverOfferConstMeta =>
      const TaskConstMeta(
        debugName: "respond_to_receiver_offer",
        argNames: ["accept"],
      );

  @override
  Future<List<NearbyReceiverInfo>> crateApiLanScanNearbyReceivers({
    required BigInt timeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_nearby_receiver_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanScanNearbyReceiversConstMeta,
        argValues: [timeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanScanNearbyReceiversConstMeta =>
      const TaskConstMeta(
        debugName: "scan_nearby_receivers",
        argNames: ["timeoutSecs"],
      );

  @override
  Future<void> crateApiReceiverSetReceiverDiscoverable({
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReceiverSetReceiverDiscoverableConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiverSetReceiverDiscoverableConstMeta =>
      const TaskConstMeta(
        debugName: "set_receiver_discoverable",
        argNames: ["enabled"],
      );

  @override
  Stream<ReceiverTransferEvent> crateApiReceiverStartReceiverTransferListener({
    required String downloadRoot,
    required String deviceName,
    required String deviceType,
  }) {
    final updates = RustStreamSink<ReceiverTransferEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(downloadRoot, serializer);
            sse_encode_String(deviceName, serializer);
            sse_encode_String(deviceType, serializer);
            sse_encode_StreamSink_receiver_transfer_event_Sse(
              updates,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 13,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiReceiverStartReceiverTransferListenerConstMeta,
          argValues: [downloadRoot, deviceName, deviceType, updates],
          apiImpl: this,
        ),
      ),
    );
    return updates.stream;
  }

  TaskConstMeta get kCrateApiReceiverStartReceiverTransferListenerConstMeta =>
      const TaskConstMeta(
        debugName: "start_receiver_transfer_listener",
        argNames: ["downloadRoot", "deviceName", "deviceType", "updates"],
      );

  @override
  Stream<SendTransferEvent> crateApiSenderStartSendTransfer({
    required SendTransferRequest request,
  }) {
    final updates = RustStreamSink<SendTransferEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_send_transfer_request(request, serializer);
            sse_encode_StreamSink_send_transfer_event_Sse(updates, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 14,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSenderStartSendTransferConstMeta,
          argValues: [request, updates],
          apiImpl: this,
        ),
      ),
    );
    return updates.stream;
  }

  TaskConstMeta get kCrateApiSenderStartSendTransferConstMeta =>
      const TaskConstMeta(
        debugName: "start_send_transfer",
        argNames: ["request", "updates"],
      );

  @override
  Stream<ReceiverPairingState> crateApiReceiverWatchReceiverPairing({
    required String downloadRoot,
    required String deviceName,
    required String deviceType,
  }) {
    final updates = RustStreamSink<ReceiverPairingState>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(downloadRoot, serializer);
            sse_encode_String(deviceName, serializer);
            sse_encode_String(deviceType, serializer);
            sse_encode_StreamSink_receiver_pairing_state_Sse(
              updates,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiReceiverWatchReceiverPairingConstMeta,
          argValues: [downloadRoot, deviceName, deviceType, updates],
          apiImpl: this,
        ),
      ),
    );
    return updates.stream;
  }

  TaskConstMeta get kCrateApiReceiverWatchReceiverPairingConstMeta =>
      const TaskConstMeta(
        debugName: "watch_receiver_pairing",
        argNames: ["downloadRoot", "deviceName", "deviceType", "updates"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ReceiverPairingState>
  dco_decode_StreamSink_receiver_pairing_state_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ReceiverTransferEvent>
  dco_decode_StreamSink_receiver_transfer_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SendTransferEvent>
  dco_decode_StreamSink_send_transfer_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ReceiverRegistration dco_decode_box_autoadd_receiver_registration(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_receiver_registration(raw);
  }

  @protected
  SendTransferRequest dco_decode_box_autoadd_send_transfer_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_send_transfer_request(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<NearbyReceiverInfo> dco_decode_list_nearby_receiver_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_nearby_receiver_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReceiverTransferFile> dco_decode_list_receiver_transfer_file(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_receiver_transfer_file)
        .toList();
  }

  @protected
  List<SelectionItem> dco_decode_list_selection_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_selection_item).toList();
  }

  @protected
  NearbyReceiverInfo dco_decode_nearby_receiver_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NearbyReceiverInfo(
      fullname: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      code: dco_decode_String(arr[2]),
      ticket: dco_decode_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ReceiverRegistration? dco_decode_opt_box_autoadd_receiver_registration(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_receiver_registration(raw);
  }

  @protected
  ReceiverPairingState dco_decode_receiver_pairing_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReceiverPairingState(
      code: dco_decode_opt_String(arr[0]),
      expiresAt: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  ReceiverRegistration dco_decode_receiver_registration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReceiverRegistration(
      code: dco_decode_String(arr[0]),
      expiresAt: dco_decode_String(arr[1]),
    );
  }

  @protected
  ReceiverTransferEvent dco_decode_receiver_transfer_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ReceiverTransferEvent(
      phase: dco_decode_receiver_transfer_phase(arr[0]),
      senderName: dco_decode_String(arr[1]),
      destinationLabel: dco_decode_String(arr[2]),
      saveRootLabel: dco_decode_String(arr[3]),
      statusMessage: dco_decode_String(arr[4]),
      itemCount: dco_decode_u_64(arr[5]),
      totalSizeBytes: dco_decode_u_64(arr[6]),
      totalSizeLabel: dco_decode_String(arr[7]),
      files: dco_decode_list_receiver_transfer_file(arr[8]),
      errorMessage: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  ReceiverTransferFile dco_decode_receiver_transfer_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReceiverTransferFile(
      path: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  ReceiverTransferPhase dco_decode_receiver_transfer_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReceiverTransferPhase.values[raw as int];
  }

  @protected
  SelectionItem dco_decode_selection_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SelectionItem(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isDirectory: dco_decode_bool(arr[2]),
      fileCount: dco_decode_u_64(arr[3]),
      totalSize: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  SelectionPreview dco_decode_selection_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SelectionPreview(
      items: dco_decode_list_selection_item(arr[0]),
      fileCount: dco_decode_u_64(arr[1]),
      totalSize: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  SendTransferEvent dco_decode_send_transfer_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SendTransferEvent(
      phase: dco_decode_send_transfer_phase(arr[0]),
      destinationLabel: dco_decode_String(arr[1]),
      statusMessage: dco_decode_String(arr[2]),
      itemCount: dco_decode_u_64(arr[3]),
      totalSize: dco_decode_u_64(arr[4]),
      bytesSent: dco_decode_u_64(arr[5]),
      remoteDeviceType: dco_decode_opt_String(arr[6]),
      errorMessage: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  SendTransferPhase dco_decode_send_transfer_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SendTransferPhase.values[raw as int];
  }

  @protected
  SendTransferRequest dco_decode_send_transfer_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SendTransferRequest(
      code: dco_decode_String(arr[0]),
      paths: dco_decode_list_String(arr[1]),
      serverUrl: dco_decode_opt_String(arr[2]),
      deviceName: dco_decode_String(arr[3]),
      deviceType: dco_decode_String(arr[4]),
      ticket: dco_decode_opt_String(arr[5]),
      lanDestinationLabel: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ReceiverPairingState>
  sse_decode_StreamSink_receiver_pairing_state_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ReceiverTransferEvent>
  sse_decode_StreamSink_receiver_transfer_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SendTransferEvent>
  sse_decode_StreamSink_send_transfer_event_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ReceiverRegistration sse_decode_box_autoadd_receiver_registration(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_receiver_registration(deserializer));
  }

  @protected
  SendTransferRequest sse_decode_box_autoadd_send_transfer_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_send_transfer_request(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<NearbyReceiverInfo> sse_decode_list_nearby_receiver_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NearbyReceiverInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_nearby_receiver_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReceiverTransferFile> sse_decode_list_receiver_transfer_file(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReceiverTransferFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_receiver_transfer_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<SelectionItem> sse_decode_list_selection_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SelectionItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_selection_item(deserializer));
    }
    return ans_;
  }

  @protected
  NearbyReceiverInfo sse_decode_nearby_receiver_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fullname = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_code = sse_decode_String(deserializer);
    var var_ticket = sse_decode_String(deserializer);
    return NearbyReceiverInfo(
      fullname: var_fullname,
      label: var_label,
      code: var_code,
      ticket: var_ticket,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReceiverRegistration? sse_decode_opt_box_autoadd_receiver_registration(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_receiver_registration(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReceiverPairingState sse_decode_receiver_pairing_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_opt_String(deserializer);
    var var_expiresAt = sse_decode_opt_String(deserializer);
    return ReceiverPairingState(code: var_code, expiresAt: var_expiresAt);
  }

  @protected
  ReceiverRegistration sse_decode_receiver_registration(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_expiresAt = sse_decode_String(deserializer);
    return ReceiverRegistration(code: var_code, expiresAt: var_expiresAt);
  }

  @protected
  ReceiverTransferEvent sse_decode_receiver_transfer_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_receiver_transfer_phase(deserializer);
    var var_senderName = sse_decode_String(deserializer);
    var var_destinationLabel = sse_decode_String(deserializer);
    var var_saveRootLabel = sse_decode_String(deserializer);
    var var_statusMessage = sse_decode_String(deserializer);
    var var_itemCount = sse_decode_u_64(deserializer);
    var var_totalSizeBytes = sse_decode_u_64(deserializer);
    var var_totalSizeLabel = sse_decode_String(deserializer);
    var var_files = sse_decode_list_receiver_transfer_file(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return ReceiverTransferEvent(
      phase: var_phase,
      senderName: var_senderName,
      destinationLabel: var_destinationLabel,
      saveRootLabel: var_saveRootLabel,
      statusMessage: var_statusMessage,
      itemCount: var_itemCount,
      totalSizeBytes: var_totalSizeBytes,
      totalSizeLabel: var_totalSizeLabel,
      files: var_files,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  ReceiverTransferFile sse_decode_receiver_transfer_file(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return ReceiverTransferFile(path: var_path, size: var_size);
  }

  @protected
  ReceiverTransferPhase sse_decode_receiver_transfer_phase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReceiverTransferPhase.values[inner];
  }

  @protected
  SelectionItem sse_decode_selection_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isDirectory = sse_decode_bool(deserializer);
    var var_fileCount = sse_decode_u_64(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    return SelectionItem(
      name: var_name,
      path: var_path,
      isDirectory: var_isDirectory,
      fileCount: var_fileCount,
      totalSize: var_totalSize,
    );
  }

  @protected
  SelectionPreview sse_decode_selection_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_selection_item(deserializer);
    var var_fileCount = sse_decode_u_64(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    return SelectionPreview(
      items: var_items,
      fileCount: var_fileCount,
      totalSize: var_totalSize,
    );
  }

  @protected
  SendTransferEvent sse_decode_send_transfer_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_send_transfer_phase(deserializer);
    var var_destinationLabel = sse_decode_String(deserializer);
    var var_statusMessage = sse_decode_String(deserializer);
    var var_itemCount = sse_decode_u_64(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    var var_bytesSent = sse_decode_u_64(deserializer);
    var var_remoteDeviceType = sse_decode_opt_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return SendTransferEvent(
      phase: var_phase,
      destinationLabel: var_destinationLabel,
      statusMessage: var_statusMessage,
      itemCount: var_itemCount,
      totalSize: var_totalSize,
      bytesSent: var_bytesSent,
      remoteDeviceType: var_remoteDeviceType,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  SendTransferPhase sse_decode_send_transfer_phase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SendTransferPhase.values[inner];
  }

  @protected
  SendTransferRequest sse_decode_send_transfer_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_paths = sse_decode_list_String(deserializer);
    var var_serverUrl = sse_decode_opt_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_ticket = sse_decode_opt_String(deserializer);
    var var_lanDestinationLabel = sse_decode_opt_String(deserializer);
    return SendTransferRequest(
      code: var_code,
      paths: var_paths,
      serverUrl: var_serverUrl,
      deviceName: var_deviceName,
      deviceType: var_deviceType,
      ticket: var_ticket,
      lanDestinationLabel: var_lanDestinationLabel,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_receiver_pairing_state_Sse(
    RustStreamSink<ReceiverPairingState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_pairing_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_receiver_transfer_event_Sse(
    RustStreamSink<ReceiverTransferEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_transfer_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_send_transfer_event_Sse(
    RustStreamSink<SendTransferEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_transfer_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_receiver_registration(
    ReceiverRegistration self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_receiver_registration(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_send_transfer_request(
    SendTransferRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_send_transfer_request(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_nearby_receiver_info(
    List<NearbyReceiverInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_nearby_receiver_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_receiver_transfer_file(
    List<ReceiverTransferFile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_receiver_transfer_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_selection_item(
    List<SelectionItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_selection_item(item, serializer);
    }
  }

  @protected
  void sse_encode_nearby_receiver_info(
    NearbyReceiverInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fullname, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.ticket, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_receiver_registration(
    ReceiverRegistration? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_receiver_registration(self, serializer);
    }
  }

  @protected
  void sse_encode_receiver_pairing_state(
    ReceiverPairingState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.code, serializer);
    sse_encode_opt_String(self.expiresAt, serializer);
  }

  @protected
  void sse_encode_receiver_registration(
    ReceiverRegistration self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.expiresAt, serializer);
  }

  @protected
  void sse_encode_receiver_transfer_event(
    ReceiverTransferEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_receiver_transfer_phase(self.phase, serializer);
    sse_encode_String(self.senderName, serializer);
    sse_encode_String(self.destinationLabel, serializer);
    sse_encode_String(self.saveRootLabel, serializer);
    sse_encode_String(self.statusMessage, serializer);
    sse_encode_u_64(self.itemCount, serializer);
    sse_encode_u_64(self.totalSizeBytes, serializer);
    sse_encode_String(self.totalSizeLabel, serializer);
    sse_encode_list_receiver_transfer_file(self.files, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_receiver_transfer_file(
    ReceiverTransferFile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_receiver_transfer_phase(
    ReceiverTransferPhase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_selection_item(SelectionItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isDirectory, serializer);
    sse_encode_u_64(self.fileCount, serializer);
    sse_encode_u_64(self.totalSize, serializer);
  }

  @protected
  void sse_encode_selection_preview(
    SelectionPreview self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_selection_item(self.items, serializer);
    sse_encode_u_64(self.fileCount, serializer);
    sse_encode_u_64(self.totalSize, serializer);
  }

  @protected
  void sse_encode_send_transfer_event(
    SendTransferEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_send_transfer_phase(self.phase, serializer);
    sse_encode_String(self.destinationLabel, serializer);
    sse_encode_String(self.statusMessage, serializer);
    sse_encode_u_64(self.itemCount, serializer);
    sse_encode_u_64(self.totalSize, serializer);
    sse_encode_u_64(self.bytesSent, serializer);
    sse_encode_opt_String(self.remoteDeviceType, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_send_transfer_phase(
    SendTransferPhase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_send_transfer_request(
    SendTransferRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_list_String(self.paths, serializer);
    sse_encode_opt_String(self.serverUrl, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_opt_String(self.ticket, serializer);
    sse_encode_opt_String(self.lanDestinationLabel, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
