// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

enum TransferPhaseData {
  connecting,
  awaitingAcceptance,
  transferring,
  finalizing,
  completed,
  cancelled,
  failed,
}

class TransferPlanData {
  final String sessionId;
  final int totalFiles;
  final BigInt totalBytes;
  final List<TransferPlanFileData> files;

  const TransferPlanData({
    required this.sessionId,
    required this.totalFiles,
    required this.totalBytes,
    required this.files,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      totalFiles.hashCode ^
      totalBytes.hashCode ^
      files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferPlanData &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          totalFiles == other.totalFiles &&
          totalBytes == other.totalBytes &&
          files == other.files;
}

class TransferPlanFileData {
  final int id;
  final String path;
  final BigInt size;

  const TransferPlanFileData({
    required this.id,
    required this.path,
    required this.size,
  });

  @override
  int get hashCode => id.hashCode ^ path.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferPlanFileData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          size == other.size;
}

class TransferSnapshotData {
  final String sessionId;
  final TransferPhaseData phase;
  final int totalFiles;
  final int completedFiles;
  final BigInt totalBytes;
  final BigInt bytesTransferred;
  final int? activeFileId;
  final BigInt? activeFileBytes;
  final BigInt? bytesPerSec;
  final BigInt? etaSeconds;

  const TransferSnapshotData({
    required this.sessionId,
    required this.phase,
    required this.totalFiles,
    required this.completedFiles,
    required this.totalBytes,
    required this.bytesTransferred,
    this.activeFileId,
    this.activeFileBytes,
    this.bytesPerSec,
    this.etaSeconds,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      phase.hashCode ^
      totalFiles.hashCode ^
      completedFiles.hashCode ^
      totalBytes.hashCode ^
      bytesTransferred.hashCode ^
      activeFileId.hashCode ^
      activeFileBytes.hashCode ^
      bytesPerSec.hashCode ^
      etaSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferSnapshotData &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          phase == other.phase &&
          totalFiles == other.totalFiles &&
          completedFiles == other.completedFiles &&
          totalBytes == other.totalBytes &&
          bytesTransferred == other.bytesTransferred &&
          activeFileId == other.activeFileId &&
          activeFileBytes == other.activeFileBytes &&
          bytesPerSec == other.bytesPerSec &&
          etaSeconds == other.etaSeconds;
}
