// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

class BridgeError implements FrbException {
  final BridgeErrorKind kind;
  final String? reason;

  const BridgeError({required this.kind, this.reason});

  @override
  int get hashCode => kind.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          reason == other.reason;
}

enum BridgeErrorKind {
  invalidInput,
  invalidCode,
  rendezvousUnavailable,
  rendezvousRejected,
  peerNotFound,
  peerAlreadyClaimed,
  lanUnavailable,
  noNearbyReceivers,
  connectionFailed,
  protocolViolation,
  transferDeclined,
  transferCancelled,
  transferFailed,
  fileConflict,
  fileNotFound,
  permissionDenied,
  io,
  internal,
}
