// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `internal_user_facing_error`, `is_retryable`, `kind`, `map_optional_user_facing_error`, `map_user_facing_error`, `message`, `recovery`, `title`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`

class UserFacingErrorData implements FrbException {
  final UserFacingErrorKindData kind;
  final String title;
  final String message;
  final String? recovery;
  final bool retryable;

  const UserFacingErrorData({
    required this.kind,
    required this.title,
    required this.message,
    this.recovery,
    required this.retryable,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      title.hashCode ^
      message.hashCode ^
      recovery.hashCode ^
      retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserFacingErrorData &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          title == other.title &&
          message == other.message &&
          recovery == other.recovery &&
          retryable == other.retryable;
}

enum UserFacingErrorKindData {
  invalidInput,
  pairingUnavailable,
  peerDeclined,
  networkUnavailable,
  connectionLost,
  permissionDenied,
  fileConflict,
  protocolIncompatible,
  cancelled,
  internal,
  other,
}
