// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_nearby_receiver`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<NearbyReceiverInfo>> scanNearbyReceivers({
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiLanScanNearbyReceivers(
  timeoutSecs: timeoutSecs,
);

class NearbyReceiverInfo {
  final String fullname;
  final String label;
  final String deviceType;
  final String code;
  final String ticket;

  const NearbyReceiverInfo({
    required this.fullname,
    required this.label,
    required this.deviceType,
    required this.code,
    required this.ticket,
  });

  @override
  int get hashCode =>
      fullname.hashCode ^
      label.hashCode ^
      deviceType.hashCode ^
      code.hashCode ^
      ticket.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearbyReceiverInfo &&
          runtimeType == other.runtimeType &&
          fullname == other.fullname &&
          label == other.label &&
          deviceType == other.deviceType &&
          code == other.code &&
          ticket == other.ticket;
}
