// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Browse for drift receivers on the LAN (`_drift._udp.local.`).
///
/// Runs the blocking mdns-sd work on a blocking thread pool thread.
Future<List<NearbyReceiverInfo>> scanNearbyReceivers({
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiLanScanNearbyReceivers(
  timeoutSecs: timeoutSecs,
);

class NearbyReceiverInfo {
  final String fullname;
  final String label;
  final String code;
  final String ticket;

  const NearbyReceiverInfo({
    required this.fullname,
    required this.label,
    required this.code,
    required this.ticket,
  });

  @override
  int get hashCode =>
      fullname.hashCode ^ label.hashCode ^ code.hashCode ^ ticket.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearbyReceiverInfo &&
          runtimeType == other.runtimeType &&
          fullname == other.fullname &&
          label == other.label &&
          code == other.code &&
          ticket == other.ticket;
}
