// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `draft_for_paths`, `map_item`, `map_preview`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<SelectionPreview> inspectPaths({required List<String> paths}) =>
    RustLib.instance.api.crateApiPreviewInspectPaths(paths: paths);

Future<SelectionPreview> appendPaths({
  required List<String> existingPaths,
  required List<String> newPaths,
}) => RustLib.instance.api.crateApiPreviewAppendPaths(
  existingPaths: existingPaths,
  newPaths: newPaths,
);

Future<SelectionPreview> removePath({
  required List<String> existingPaths,
  required String removedPath,
}) => RustLib.instance.api.crateApiPreviewRemovePath(
  existingPaths: existingPaths,
  removedPath: removedPath,
);

class SelectionItem {
  final String name;
  final String path;
  final bool isDirectory;
  final BigInt fileCount;
  final BigInt totalSize;

  const SelectionItem({
    required this.name,
    required this.path,
    required this.isDirectory,
    required this.fileCount,
    required this.totalSize,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDirectory.hashCode ^
      fileCount.hashCode ^
      totalSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelectionItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDirectory == other.isDirectory &&
          fileCount == other.fileCount &&
          totalSize == other.totalSize;
}

class SelectionPreview {
  final List<SelectionItem> items;
  final BigInt fileCount;
  final BigInt totalSize;

  const SelectionPreview({
    required this.items,
    required this.fileCount,
    required this.totalSize,
  });

  @override
  int get hashCode => items.hashCode ^ fileCount.hashCode ^ totalSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelectionPreview &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          fileCount == other.fileCount &&
          totalSize == other.totalSize;
}
