// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_expired`, `log`, `register_new_idle_receiver`, `replace_idle_receiver`, `take_idle_receiver`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IdleReceiver`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<IdleReceiverRegistration> registerIdleReceiver({String? serverUrl}) =>
    RustLib.instance.api.crateApiReceiverRegisterIdleReceiver(
      serverUrl: serverUrl,
    );

Future<IdleReceiverRegistration> ensureIdleReceiver({String? serverUrl}) =>
    RustLib.instance.api.crateApiReceiverEnsureIdleReceiver(
      serverUrl: serverUrl,
    );

Future<IdleReceiverRegistration?> currentIdleReceiverRegistration() =>
    RustLib.instance.api.crateApiReceiverCurrentIdleReceiverRegistration();

class IdleReceiverRegistration {
  final String code;
  final String expiresAt;

  const IdleReceiverRegistration({required this.code, required this.expiresAt});

  @override
  int get hashCode => code.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdleReceiverRegistration &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          expiresAt == other.expiresAt;
}
