// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_service`, `ensure_receiver_service`, `existing_service_for_config`, `map_event`, `map_file_row`, `map_pairing_state`, `map_registration`, `pairing_registration`, `replace_pairing_task`, `replace_updates_task`, `scan_nearby_with_receiver`, `set_discoverable`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeReceiverConfig`, `BridgeReceiverState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ReceiverRegistration> registerReceiver({
  String? serverUrl,
  required String deviceName,
}) => RustLib.instance.api.crateApiReceiverRegisterReceiver(
  serverUrl: serverUrl,
  deviceName: deviceName,
);

Future<ReceiverRegistration> ensureReceiverRegistration({
  String? serverUrl,
  required String deviceName,
}) => RustLib.instance.api.crateApiReceiverEnsureReceiverRegistration(
  serverUrl: serverUrl,
  deviceName: deviceName,
);

Future<ReceiverRegistration?> currentReceiverRegistration() =>
    RustLib.instance.api.crateApiReceiverCurrentReceiverRegistration();

Stream<ReceiverPairingState> watchReceiverPairing({
  String? serverUrl,
  required String downloadRoot,
  required String deviceName,
  required String deviceType,
}) => RustLib.instance.api.crateApiReceiverWatchReceiverPairing(
  serverUrl: serverUrl,
  downloadRoot: downloadRoot,
  deviceName: deviceName,
  deviceType: deviceType,
);

Future<void> setReceiverDiscoverable({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiReceiverSetReceiverDiscoverable(enabled: enabled);

Stream<ReceiverTransferEvent> startReceiverTransferListener({
  String? serverUrl,
  required String downloadRoot,
  required String deviceName,
  required String deviceType,
}) => RustLib.instance.api.crateApiReceiverStartReceiverTransferListener(
  serverUrl: serverUrl,
  downloadRoot: downloadRoot,
  deviceName: deviceName,
  deviceType: deviceType,
);

Future<void> respondToReceiverOffer({required bool accept}) =>
    RustLib.instance.api.crateApiReceiverRespondToReceiverOffer(accept: accept);

Future<void> cancelReceiverTransfer() =>
    RustLib.instance.api.crateApiReceiverCancelReceiverTransfer();

class ReceiverPairingState {
  final String? code;
  final String? expiresAt;

  const ReceiverPairingState({this.code, this.expiresAt});

  @override
  int get hashCode => code.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverPairingState &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          expiresAt == other.expiresAt;
}

class ReceiverRegistration {
  final String code;
  final String expiresAt;

  const ReceiverRegistration({required this.code, required this.expiresAt});

  @override
  int get hashCode => code.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverRegistration &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          expiresAt == other.expiresAt;
}

class ReceiverTransferEvent {
  final ReceiverTransferPhase phase;
  final String senderName;
  final String senderDeviceType;
  final String destinationLabel;
  final String saveRootLabel;
  final String statusMessage;
  final BigInt itemCount;
  final BigInt totalSizeBytes;
  final BigInt bytesReceived;
  final String totalSizeLabel;
  final List<ReceiverTransferFile> files;
  final String? errorMessage;

  const ReceiverTransferEvent({
    required this.phase,
    required this.senderName,
    required this.senderDeviceType,
    required this.destinationLabel,
    required this.saveRootLabel,
    required this.statusMessage,
    required this.itemCount,
    required this.totalSizeBytes,
    required this.bytesReceived,
    required this.totalSizeLabel,
    required this.files,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      senderName.hashCode ^
      senderDeviceType.hashCode ^
      destinationLabel.hashCode ^
      saveRootLabel.hashCode ^
      statusMessage.hashCode ^
      itemCount.hashCode ^
      totalSizeBytes.hashCode ^
      bytesReceived.hashCode ^
      totalSizeLabel.hashCode ^
      files.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverTransferEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          senderName == other.senderName &&
          senderDeviceType == other.senderDeviceType &&
          destinationLabel == other.destinationLabel &&
          saveRootLabel == other.saveRootLabel &&
          statusMessage == other.statusMessage &&
          itemCount == other.itemCount &&
          totalSizeBytes == other.totalSizeBytes &&
          bytesReceived == other.bytesReceived &&
          totalSizeLabel == other.totalSizeLabel &&
          files == other.files &&
          errorMessage == other.errorMessage;
}

class ReceiverTransferFile {
  final String path;
  final BigInt size;

  const ReceiverTransferFile({required this.path, required this.size});

  @override
  int get hashCode => path.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverTransferFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          size == other.size;
}

enum ReceiverTransferPhase {
  connecting,
  offerReady,
  receiving,
  completed,
  cancelled,
  failed,
  declined,
}
