// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'transfer.dart';

// These functions are ignored because they are not marked as `pub`: `cancel_send_session`, `fallback_destination_label`, `format_code_label`, `map_event`, `map_phase`, `map_plan_file`, `map_plan`, `map_snapshot`, `terminal_event_for_app_error`, `terminal_internal_failure_event`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

Stream<SendTransferEvent> startSendTransfer({
  required SendTransferRequest request,
}) => RustLib.instance.api.crateApiSenderStartSendTransfer(request: request);

Future<void> cancelActiveSendTransfer() =>
    RustLib.instance.api.crateApiSenderCancelActiveSendTransfer();

class SendTransferEvent {
  final SendTransferPhase phase;
  final String destinationLabel;
  final String statusMessage;
  final BigInt itemCount;
  final BigInt totalSize;
  final BigInt bytesSent;
  final TransferPlanData? plan;
  final TransferSnapshotData? snapshot;
  final String? remoteDeviceType;
  final UserFacingErrorData? error;

  const SendTransferEvent({
    required this.phase,
    required this.destinationLabel,
    required this.statusMessage,
    required this.itemCount,
    required this.totalSize,
    required this.bytesSent,
    this.plan,
    this.snapshot,
    this.remoteDeviceType,
    this.error,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      destinationLabel.hashCode ^
      statusMessage.hashCode ^
      itemCount.hashCode ^
      totalSize.hashCode ^
      bytesSent.hashCode ^
      plan.hashCode ^
      snapshot.hashCode ^
      remoteDeviceType.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTransferEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          destinationLabel == other.destinationLabel &&
          statusMessage == other.statusMessage &&
          itemCount == other.itemCount &&
          totalSize == other.totalSize &&
          bytesSent == other.bytesSent &&
          plan == other.plan &&
          snapshot == other.snapshot &&
          remoteDeviceType == other.remoteDeviceType &&
          error == other.error;
}

enum SendTransferPhase {
  connecting,
  waitingForDecision,
  accepted,
  declined,
  sending,
  completed,
  cancelled,
  failed,
}

class SendTransferRequest {
  final String code;
  final List<String> paths;
  final String? serverUrl;
  final String deviceName;
  final String deviceType;
  final String? ticket;
  final String? lanDestinationLabel;

  const SendTransferRequest({
    required this.code,
    required this.paths,
    this.serverUrl,
    required this.deviceName,
    required this.deviceType,
    this.ticket,
    this.lanDestinationLabel,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      paths.hashCode ^
      serverUrl.hashCode ^
      deviceName.hashCode ^
      deviceType.hashCode ^
      ticket.hashCode ^
      lanDestinationLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTransferRequest &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          paths == other.paths &&
          serverUrl == other.serverUrl &&
          deviceName == other.deviceName &&
          deviceType == other.deviceType &&
          ticket == other.ticket &&
          lanDestinationLabel == other.lanDestinationLabel;
}
