// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `device_type_to_str`, `display_destination_label`, `format_error_chain`, `log`, `map_progress`, `parse_device_type`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

Stream<SendTransferEvent> startSendTransfer({
  required SendTransferRequest request,
}) => RustLib.instance.api.crateApiSenderStartSendTransfer(request: request);

class SendTransferEvent {
  final SendTransferPhase phase;
  final String destinationLabel;
  final String statusMessage;
  final BigInt itemCount;
  final BigInt totalSize;
  final BigInt bytesSent;

  /// `"phone"` or `"laptop"`.
  final String? remoteDeviceType;
  final String? errorMessage;

  const SendTransferEvent({
    required this.phase,
    required this.destinationLabel,
    required this.statusMessage,
    required this.itemCount,
    required this.totalSize,
    required this.bytesSent,
    this.remoteDeviceType,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      destinationLabel.hashCode ^
      statusMessage.hashCode ^
      itemCount.hashCode ^
      totalSize.hashCode ^
      bytesSent.hashCode ^
      remoteDeviceType.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTransferEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          destinationLabel == other.destinationLabel &&
          statusMessage == other.statusMessage &&
          itemCount == other.itemCount &&
          totalSize == other.totalSize &&
          bytesSent == other.bytesSent &&
          remoteDeviceType == other.remoteDeviceType &&
          errorMessage == other.errorMessage;
}

enum SendTransferPhase {
  connecting,
  waitingForDecision,
  sending,
  completed,
  failed,
}

class SendTransferRequest {
  final String code;
  final List<String> paths;
  final String? serverUrl;
  final String deviceName;

  /// `"phone"` or `"laptop"`.
  final String deviceType;

  const SendTransferRequest({
    required this.code,
    required this.paths,
    this.serverUrl,
    required this.deviceName,
    required this.deviceType,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      paths.hashCode ^
      serverUrl.hashCode ^
      deviceName.hashCode ^
      deviceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTransferRequest &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          paths == other.paths &&
          serverUrl == other.serverUrl &&
          deviceName == other.deviceName &&
          deviceType == other.deviceType;
}
